export const storeProducts = [
  {
    id: 1,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem1.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 2000,
    price2: 20000,
    seller: "Mohammed",
    moq: "1 bag",
    review: 3,
    orders: 6,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },

  {
    id: 2,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem3.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 5000,
    price2: 250000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 5,
    orders: 2,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 3,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem2.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 100,
    price2: 20000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 10,
    orders: 100,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 4,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem4.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 500,
    price2: 20000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 5,
    orders: 100,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 5,
    title: "Tomato-Bag from Kano",
    img: "Image/sample 1.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 50000,
    price2: 200000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 12,
    orders: 100,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 6,
    title: "Apple from Accra",
    img: "Image/sample 2.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 10000,
    price2: 20000,
    seller: "Mohammed",
    moq: "50pieces",
    review: 50,
    orders: 100,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 7,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem3.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 50,
    price2: 20000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 50,
    orders: 100,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 8,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem3.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 5000,
    price2: 20000,
    seller: "Mohammed",
    moq: "1 basket",
    review: 50,
    orders: 100,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 9,
    title: "Tomato-Bag from Kano",
    img: "Image/sample 1.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 10000,
    price2: 20000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 50,
    orders: 100,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 10,
    title: "Tomato-Bag from Kano",
    img: "Image/sample 2.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 10000,
    price2: 20000,
    seller: "Mohammed",
    moq: "50pieces",
    review: 50,
    orders: 1,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 11,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem3.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 1250,
    price2: 20000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 50,
    orders: 10,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 12,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem3.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    price: 900,
    price2: 20000,
    seller: "Mohammed",
    moq: "1 basket",
    review: 50,
    orders: 15,
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Tomato-Bag from Kano",
  img: "Image/CateItem2.png",
  price: 20000,
  price2: 100000,
  seller: "Mohammed",
  info:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
  inCart: false,
  count: 0,
  total: 0,
};
