export const storeProducts = [
  {
    id: 1,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem1.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    productImg1: "Image/description1.png",
    productImg2: "Image/description2.png",
    productImg3: "Image/description3.png",
    productImg4: "Image/description4.png",
    price: 2000,
    price2: 20000,
    seller: "Mohammed",
    moq: "1 bag",
    review: 3,
    orders: 6,
    companyInfo:
      "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain.These cases are perfectly simple and easy to distinguish.In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided.But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted.The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.",
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },

  {
    id: 2,
    title: "Tomato-Bag from Kano",
    img: "Image/clothes.png",
    img1: "Image/clothe1.png",
    img2: "Image/clothe2.png",
    img3: "Image/clothe3.png",
    productImg1: "Image/description1.png",
    productImg2: "Image/description2.png",
    productImg3: "Image/description3.png",
    productImg4: "Image/description4.png",
    price: 5000,
    price2: 250000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 5,
    orders: 2,
    companyInfo:
      "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain.These cases are perfectly simple and easy to distinguish.In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided.But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted.The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.",
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 3,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem2.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    productImg1: "Image/description1.png",
    productImg2: "Image/description2.png",
    productImg3: "Image/description3.png",
    productImg4: "Image/description4.png",
    price: 100,
    price2: 20000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 10,
    orders: 100,
    companyInfo:
      "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain.These cases are perfectly simple and easy to distinguish.In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided.But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted.The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.",
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 4,
    title: "Tomato-Bag from Kano",
    img: "Image/CateItem4.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    productImg1: "Image/description1.png",
    productImg2: "Image/description2.png",
    productImg3: "Image/description3.png",
    productImg4: "Image/description4.png",
    price: 500,
    price2: 20000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 5,
    orders: 100,
    companyInfo:
      "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain.These cases are perfectly simple and easy to distinguish.In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided.But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted.The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.",
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 5,
    title: "Tomato-Bag from Kano",
    img: "Image/sample 1.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    productImg1: "Image/description1.png",
    productImg2: "Image/description2.png",
    productImg3: "Image/description3.png",
    productImg4: "Image/description4.png",
    price: 50000,
    price2: 200000,
    seller: "Mohammed",
    moq: "20pieces",
    review: 12,
    orders: 100,
    companyInfo:
      "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain.These cases are perfectly simple and easy to distinguish.In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided.But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted.The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.",
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  },
  {
    id: 6,
    title: "Apple from Accra",
    img: "Image/sample 2.png",
    img1: "Image/sample 1.png",
    img2: "Image/CateItem1.png",
    img3: "Image/sample 1.png",
    productImg1: "Image/description1.png",
    productImg2: "Image/description2.png",
    productImg3: "Image/description3.png",
    productImg4: "Image/description4.png",
    price: 10000,
    price2: 20000,
    seller: "Mohammed",
    moq: "50pieces",
    review: 50,
    orders: 100,
    companyInfo:
      "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain.These cases are perfectly simple and easy to distinguish.In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided.But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted.The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.",
    info:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
    inCart: false,
    total: 0,
  }
 
];

export const detailProduct = {
  id: 1,
  title: "Tomato-Bag from Kano",
  img: "Image/CateItem2.png",
  price: 20000,
  price2: 100000,
  seller: "Mohammed",
  info:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in",
  inCart: false,
  count: 0,
  total: 0,
};
